parameters:

    ez_loremipsum_bundle.faker.default_locale: ~

    ez_loremipsum_bundle.reference_resolver.faker.class: Kaliop\eZLoremIpsumBundle\Core\ReferenceResolver\FakerResolver

services:

    ez_loremipsum_bundle.reference_resolver.faker:
        class: '%ez_loremipsum_bundle.reference_resolver.faker.class%'
        arguments:
            - '%ez_loremipsum_bundle.faker.default_locale%'
        tags:
            - { name: ez_migration_bundle.reference_resolver.customreference }
