parameters:

    ez_loremipsum_bundle.reference_resolver.lorem_ipsum.class: Kaliop\eZLoremIpsumBundle\Core\ReferenceResolver\LoremIpsumResolver

services:

    ez_loremipsum_bundle.reference_resolver.lorem_ipsum:
        class: '%ez_loremipsum_bundle.reference_resolver.lorem_ipsum.class%'
        #arguments: []
        tags:
            - { name: ez_migration_bundle.reference_resolver.customreference }
