parameters:
    # change this if you want to use a different locale than the one gotten from the current siteaccess
    ez_loremipsum_bundle.faker.locale: ~

    ez_loremipsum_bundle.reference_resolver.faker.class: Kaliop\eZLoremIpsumBundle\Core\ReferenceResolver\FakerResolver

services:

    ez_loremipsum_bundle.reference_resolver.faker:
        class: '%ez_loremipsum_bundle.reference_resolver.faker.class%'
        arguments:
            - '@ezpublish.config.resolver'
            - '@ez_migration_bundle.reference_resolver.customreference'
            - '%ez_loremipsum_bundle.faker.locale%'
        tags:
            - { name: ez_migration_bundle.reference_resolver.customreference }
